;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Ammo",DevComment="")
+GameplayTagList=(Tag="Ammo.Arrow",DevComment="화살")
+GameplayTagList=(Tag="Ammo.Pistol",DevComment="권총 탄약")
+GameplayTagList=(Tag="Ammo.Rifle",DevComment="라이플/돌격소총 탄약 ")
+GameplayTagList=(Tag="Ammo.Shotgun",DevComment="샷건 탄약")
+GameplayTagList=(Tag="Ammo.Sniper",DevComment="저격총 탄약")
+GameplayTagList=(Tag="EnhancedInput.Modes.Inventory",DevComment="인벤토리가 열려있을  때")

